[USERS.om]
name = "O&M User"
password = "om"
role = "O&M"

[USERS.crm]
name = "CRM User"
password = "crm"
role = "CRM"

[USERS.admin]
name = "Admin User"
password = "admin"
role = "Admin"

MONGO_URI = "mongodb+srv://selvaram58_db_user:cFhijYBal60CGpAi@dgr-demo.dh1kxon.mongodb.net/"
